### ISSUE TITLE
Missing directories and or files in version 2.4

### ISSUE THREAD

**Issue by amjadyahya1** [NinevaStudios/iOS-Goodies-Unity-Plugin-Documentation#2]
When running on iOS device using Xcode, it throws: 
no such file or directory: '/Users/../Libraries/IOSGoodies/Editor/iOS/Other/GoodiesDateTimePicker.m'
clang: error: no input files

**Comment by TarasOsiris** [comment]
Hi, you should try creating a clean project and try importing and testing the plugin there, if you have updated the plugin recently, make sure you have deleted the older version before importing the update

**Comment by amjadyahya1** [comment]
Indeed, I have updated the plugin from an earlier version. I have deleted the iOS project and built it again with no errors. Thanks a lot.

**Comment by TarasOsiris** [comment]
@amjadyahya1 You are welcome! Also please write us a review on Asset Store if you enjoy the plugin and the support of course, it will help us a lot, thanks

**Comment by amjadyahya1** [comment]
Just did.
